/**
 * Harness sync renderer (PRD-004c FR-2 / FR-3 / FR-7).
 *
 * Reads the canonical identity files from the workspace directory and writes
 * per-harness copies, each stamped with a do-not-edit header. Destinations are
 * injected (see `HarnessTarget`) — real destinations are registered by the
 * integrations module (PRD-019); in tests the targets point at temp dirs.
 *
 * The renderer is IDEMPOTENT: given unchanged canonical files, it produces
 * byte-identical output on every call. The caller (file-watcher) skips a git
 * commit when no bytes changed (c-AC-4).
 *
 * This module has NO dependency on the watcher or git-sync — it is a pure
 * read-from-workspace / write-to-targets function, so it is trivially testable
 * in isolation.
 */

import * as fs from "node:fs/promises";
import * as path from "node:path";

// ── Do-not-edit header (c-AC-1 / FR-3) ───────────────────────────────────────
//
// Every generated harness copy is PREPENDED with this header so a developer
// who opens the file sees immediately that it is daemon-generated and that
// manual edits will be overwritten. The header embeds the source workspace
// path and the timestamp of generation so the provenance is traceable.

/** Build the do-not-edit header for a generated harness copy. */
export function buildDoNotEditHeader(opts: {
	readonly sourceFile: string;
	readonly targetName: string;
	readonly generatedAt: string; // ISO-8601
}): string {
	return [
		"# ============================================================",
		"# DO NOT EDIT — this file is auto-generated by the Honeycomb daemon.",
		`# Source:    ${opts.sourceFile}`,
		`# Target:    ${opts.targetName}`,
		`# Generated: ${opts.generatedAt}`,
		"# Manual edits will be overwritten on the next identity-file change.",
		"# To update this file, edit the canonical source listed above.",
		"# ============================================================",
		"",
	].join("\n");
}

/** A single per-harness copy destination. */
export interface HarnessTarget {
	/** Harness name, e.g. `claude-code`, `codex`, `cursor`. */
	readonly name: string;
	/**
	 * Absolute path to the per-harness copy file, e.g.
	 * `~/.claude/CLAUDE.md`. In tests this is a path under a temp dir.
	 *
	 * NOTE: The Honeycomb daemon resolves the actual on-disk path from the
	 * connectors registry (PRD-019). This module accepts the resolved path
	 * verbatim and does not interpret `~` — the caller must expand it.
	 */
	readonly outputPath: string;
	/**
	 * The canonical identity file(s) to concatenate for this harness copy,
	 * relative to the workspace directory. When absent, defaults to the full
	 * CANONICAL_IDENTITY_FILES set.
	 */
	readonly sourceFiles?: readonly string[];
}

/** The canonical identity-file names the watcher monitors (FR-1). */
export const CANONICAL_IDENTITY_FILES: readonly string[] = Object.freeze([
	"agent.yaml",
	"AGENTS.md",
	"SOUL.md",
	"MEMORY.md",
	"IDENTITY.md",
	"USER.md",
]);

/**
 * Result of a single harness-copy write: whether the bytes actually changed.
 * The git-sync helper uses this to decide whether to commit.
 */
export interface SyncResult {
	readonly target: string; // harness name
	readonly outputPath: string;
	/** True when the file was written (content changed or file was absent). */
	readonly changed: boolean;
	/** Error message, if the render for this target failed. */
	readonly error?: string;
}

/**
 * Read a canonical identity file; return its content as a string, or `null`
 * if the file does not exist (removed/renamed — FR-8).
 */
async function readCanonical(filePath: string): Promise<string | null> {
	try {
		return await fs.readFile(filePath, "utf8");
	} catch (err) {
		if (err instanceof Error && "code" in err && (err as NodeJS.ErrnoException).code === "ENOENT") {
			return null;
		}
		throw err;
	}
}

/**
 * Ensure the parent directory of `filePath` exists (creates intermediate dirs
 * if needed, like `mkdir -p`). Required before writing harness copies.
 */
async function ensureDir(filePath: string): Promise<void> {
	await fs.mkdir(path.dirname(filePath), { recursive: true });
}

/**
 * Build the full content for a harness copy: do-not-edit header + the
 * concatenated canonical sources.
 *
 * Sections are separated by a blank line. A missing canonical file is noted
 * as a one-line comment so the copy is still valid (FR-8 graceful reconcile).
 */
function buildHarnessCopyContent(opts: {
	readonly sourceDir: string;
	readonly sourceResults: ReadonlyMap<string, string | null>;
	readonly targetName: string;
	readonly sourceFileNames: readonly string[];
	readonly generatedAt: string;
}): string {
	const { sourceDir, sourceResults, targetName, sourceFileNames, generatedAt } = opts;
	const parts: string[] = [];

	// Header (c-AC-1 / FR-3)
	parts.push(
		buildDoNotEditHeader({
			sourceFile: path.join(sourceDir, sourceFileNames.join(", ")),
			targetName,
			generatedAt,
		}),
	);

	// Content: each source file's content, or a placeholder note if missing
	for (const name of sourceFileNames) {
		const content = sourceResults.get(name);
		if (content === null || content === undefined) {
			// File was removed/renamed (FR-8) — leave a note so the copy is coherent
			parts.push(`# [${name} was not found — file removed or not yet created]\n`);
		} else {
			parts.push(content);
			// Ensure there is a trailing newline before the next section
			if (!content.endsWith("\n")) {
				parts.push("\n");
			}
		}
	}

	return parts.join("\n");
}

/**
 * Run the harness sync: read canonical files from `workspaceDir` and write
 * each per-harness copy. Returns one `SyncResult` per target.
 *
 * Never throws: per-target errors are caught and surfaced in `SyncResult.error`
 * so the watcher can log them without crashing (FR-8 / guide 09-error-handling).
 *
 * @param workspaceDir  Absolute path to the workspace root.
 * @param targets       Harness copy destinations (injected — see `HarnessTarget`).
 * @param now           ISO-8601 timestamp for the do-not-edit header (injected
 *                      so tests are deterministic — the watcher passes `clock()`).
 */
export async function syncHarnessCopies(
	workspaceDir: string,
	targets: readonly HarnessTarget[],
	now: string,
): Promise<SyncResult[]> {
	// ── 1. Read all canonical identity files once ─────────────────────────────
	const canonicalContents = new Map<string, string | null>();
	await Promise.all(
		CANONICAL_IDENTITY_FILES.map(async (name) => {
			const filePath = path.join(workspaceDir, name);
			canonicalContents.set(name, await readCanonical(filePath));
		}),
	);

	// ── 2. Write each harness copy ────────────────────────────────────────────
	return Promise.all(
		targets.map(async (target): Promise<SyncResult> => {
			const sourceFileNames = target.sourceFiles ?? CANONICAL_IDENTITY_FILES;
			try {
				const newContent = buildHarnessCopyContent({
					sourceDir: workspaceDir,
					sourceResults: canonicalContents,
					targetName: target.name,
					sourceFileNames,
					generatedAt: now,
				});

				// Read existing copy to detect whether content actually changed (c-AC-4)
				let existingContent: string | null = null;
				try {
					existingContent = await fs.readFile(target.outputPath, "utf8");
				} catch (err) {
					if (!(err instanceof Error && "code" in err && (err as NodeJS.ErrnoException).code === "ENOENT")) {
						throw err;
					}
				}

				if (existingContent === newContent) {
					// Byte-identical — no write needed (c-AC-4 idempotency)
					return { target: target.name, outputPath: target.outputPath, changed: false };
				}

				await ensureDir(target.outputPath);
				await fs.writeFile(target.outputPath, newContent, "utf8");
				return { target: target.name, outputPath: target.outputPath, changed: true };
			} catch (err) {
				const message = err instanceof Error ? err.message : String(err);
				return {
					target: target.name,
					outputPath: target.outputPath,
					changed: false,
					error: `harness sync failed for ${target.name}: ${message}`,
				};
			}
		}),
	);
}
